global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Métricas da aplicação Flask
  - job_name: "task-manager"
    static_configs:
      - targets: ["app:5000"]
    metrics_path: "/metrics"

  # Métricas do próprio Prometheus
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
